#include <stddef.h>
#include <stdint.h>
#include "../include/printf_lib.h"

static void kwait() {
    int i;
    for (i = 0; i < 352147; i++) {
        asm("nop");
    }
}

static void clears(){
    int i;
    for (i = 0; i < 50; ++i) {
        kprintfln("");
    }
}

void rick(){
    while (1) {
        kprintfln("oyyyyyyyyyyyyyyyyyyyhhhhhhhhhyssssssyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyhhhhhhhhhhhs");
        kprintfln("syyyyyyhhhyyyyhhyyhyyyyyyyyyyyyysssyhhhhyyyyyyyyyyyyyyyyhhhhhhhhhhyhyyyyhhhhhhhhyyyyyyyyhhhhhhhhhhhs");
        kprintfln("syyyhhhhhhhhdddhhhddhhhhhhhyyyyyyyyyysssssyyssyyhhhhhhyyyyyyyyyhhyyyyyyyyhhyyyyyyyyyyyyyhhhhhhhhhhhs");
        kprintfln("syyhhhhhddddddhhhhddddddddddddyyyyyyyhhyyyssyyyhhhhhhhhyyyyyyyyyyyyyyyyyyyyhhyyyhhhyyhhhyyyyyyyhhhhs");
        kprintfln("shhhhhhdddddhhhhdddddddddddddhyyyyyyyhhhhyyyhhhhhhhhhhhhhyyyhhhhhyyyyyyhhhhhhhhhhhhyyyhhhyyyyyyyyyys");
        kprintfln("shhddhhhhhdhhhhddmmmdddddhyyyhhyyyhhyyyyyssyyyyhyyhhhhhhhyyyyyyyyyyyyyyyyhhhhhhhhhhyyyyyyhhhyyyyyyys");
        kprintfln("ydddmmdhhhhhhhdmmmmdhhhhyyyhddhyyyhhyyyhhyyso+//////++osyyyyyyyyyyhyyyyyyyyyyhhhhhhhhyyyyhhhyyyyyyyo");
        kprintfln("hdddmmmdhhhhdmmmmdhhhhhhhhhddmhhyyyyyhhyo/::--........-:shhdddhyyyyyyyyhhyyyyyyyyhhhhhyyyyyyyyyhyyyo");
        kprintfln("hdddmmmmddhhhdddhhhhddmmddhhdmhhyyyhdho+:-..........```./hdddddhhyyyyyyhhhyyyyyyyyyhddhhyyyyyhhhhhhs");
        kprintfln("hmmmmmmmmdhhhhhhdhhhddmddhhhhhhyyyyhdds:-....-:///--.`..-shhdddddhyyssyhhyyhhdhhyyyyyhhhyyyhhhhhhhhy");
        kprintfln("hmmmmmmmmdhhddhddmdhhhddhhdddhyyyyhdmddh+/::/+ooso/:-...-+hddddddhyyssyyyyyyhhhhhyyyyyyyyyhddddddhhy");
        kprintfln("hmmmmmmmmdddmmdhddhdddhhhmmmmdhhyyhyhhddo+///++ooso/::--:/hdddddhhyyssyyhdhyyyyyyyhhhyyyyyyhddddddhy");
        kprintfln("hmmmmdddddddmmmddhhdmmmdhdmmmdhyyhdhyyhhs///////+oos+///+oyhddhhyyyyyyyhddddyyhhyyyyyyhdhyydddddddhy");
        kprintfln("hmmddhhhhhhhhhdhhhhdmmmdhdmdmdyyyhhhyyyys/:/+/::/+ooooo+oyyyyyyyyyhyyyyyhddhyhdhhhyyyhddhyyyyhhddhhs");
        kprintfln("ydhhdddddddddddhhhhhhddmhhdddhyyyyyyhdddho++so//++ooosssyhyyhhhyyyyyyyyyhhdhyhddhyyyyyyyyyyyyyyhhhhs");
        kprintfln("shhdmmmmmmmmmmhhdmdhhhdddhhhdhyyyyhddddhys++++///+o+:///syyyyhhdhyyyyyyyhhhyhddhyyyyyyyyhyyyyyyyyhhs");
        kprintfln("shhdmmmdmmmmdhhhdddhhhhhhhhhyyyyyyhdddhyyys///////++:///syyyyyyhddhyyyyyyyyyyhhyyyhhyyhhddhhhhhhyyyo");
        kprintfln("shddmmmdmmmmdhhhhhyyyyyyhdddhyyyyyyhhyyyyhhs+///++++:///syyyyyyyhhhyyyyyyhhhyyyyyyhdhyyhdddhhdddhyyo");
        kprintfln("sddmmdddddddhhhhdhhhyyyyhdddhyysyyyyyssoo+//o/::://+//+o+s/:+oosyyyyyyyyhhhhhyyyyyyyyyyyddddddddhyyo");
        kprintfln("shdhhhhhhhhhhhddddhyyyyyyhhdhysyysso+:-.```.++:::://+os/+y+....-:/oossyyhhhhyyyyyyhhyyyyyhhhhhhhhhyo");
        kprintfln("syyhhhhddhhddmddddhyhhyyyyhhhsso+:-.````````/oso////+yhsyy/.```````.-:+oyhhhyyyyyyhddhhyyyyyyyyhhhho");
        kprintfln("shhddddddhhhdddddhyhddhyysyhy:..````````````/+ssso//+syyys.````````````.-+hyyyyhhyhdddddhyyyyyyysyyo");
        kprintfln("sddddddddhhhhddddhyhdhyyyyyy/.``````````````-:///+/++oss+.```````````````.oyyyhhhyyhdddddyyhhddhyyyo");
        kprintfln("shdddddddhhhyhddhyydhyssyhyy-````````````````.-::::://::..````````````````/yyyyyhhyyhddhyyyhhhhddhho");
        kprintfln("syhdddhhhhddhhyhyyyyyyyyyyyy/````````````````.:///////:-.`````````````````/yyyyyyhyyhdhyyyyyhhhddhho");
        kprintfln("yhhyhhhhhddddhyyyyyyyhhhhhyy:``````````````-///+++/::::-.`````````````````+yyhhyyyyyyysyhhyyyyhhhyyo");
        kprintfln("shhhyhhddddddhhysyyhhhhhhhhs.````````````./+//++++/:::-.``````````````````/hhhhhhyyyyyyhhhhyyyyyyyys");
        kprintfln("yddhhhdddddhhhhysyhhhhhhhhy:````````````.++///+++/::::-.``````````````````/yhhhhhhyyyyhhhhhhyyyyyhhs");
        kprintfln("ydhyyhddddddddhysssyhhhhhhs-````````````:::://+//:---:-.````````````   ``.:yyhhhhhhyyhhhhhhhhhyyyhhs");
        kprintfln("ydhyyhddddddddhssssyyhhhhy/.``````````.-::-::::--------.```````````    ``.:yyyyhhhyyyhhhhhhhhhyyyhhs");
        kprintfln("yhyyyyhhdddhhhyssyyyyyyyyo.````````.....----.``..-----.```````````     ``.-syyyyyyyyyyhhhhhhhhyyyyhs");
        kprintfln("sysssyyyyyyyyysssyyyyssyy/..````````````...````......-.``````````      ``.:sssyyyyyyyyyyyyyyyyyyyyys");
        kprintfln("+oooooosssssssooossssssss:.`````` ```  ```   ```.......`  ` ````       ``.:oosssssssssssssssssssssso");
        kprintfln("/o+/++oooooooo++++o++++++.`                   ```.....`                ```-+++++oooooooooooooooooooo");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();
        kprintfln("yddddddhhhhhhhhhdddddddddmmmdhyyhhhhhddddddddhddhhyhddmdmmmddddhyyyyyyyyhddhhhhhdhhhdhhhhhhhyyyyhhhs");
        kprintfln("yddddhhhhhhhhhddddddddhhhhhhhhhhhhhhddddhyyyyyyyyyhhhhhddddddmddhyyyyyyyhdddddddddhddhhhhhhhhyyyhhhs");
        kprintfln("ydddhhhhhhhddmmdhdmmmdddddhhhhhhhhhhhhyyyyhhyyyhddmmddhhhhdhhhhhhyyyyyyyyyhhhhhdddddddddddhhhyyhhhhs");
        kprintfln("yhhhhhhddddmmddhhdmmmmmmmmmmmmddddddddddhhyyhhhdmmmmmmddhhhhhhhhyyyyyyyyyyhddddmmmmddmmddhhyyyyhhhhs");
        kprintfln("yhhhhhdmmmmmdddddmmmmmmmmmmmmddddddddmmmddhhddmmmmmmmmmmmdhdmddddyyyyyyddddmmmmmmmmdddmmdhyyyyyhhhhs");
        kprintfln("shddddhhddmddddmmmmmmmmmdddddddddddddhhhhhhhhhddddddmmmmddhhddhhyyyyyyyyhddddmmmmmmdddhhdddhhyyhhhhs");
        kprintfln("ydmmmmmdddddddmmmmmmdddhhhhdmmddhhddhhdddddhhyhysooosssyhhdhhhyyyhhyyyyhyyyyhddmmmmmmdhhhdddhhhhddhy");
        kprintfln("hmmmmmmmdddddmmmmmdddddddddmmNddddddddmmmmmdysoo/----:::+ydddddhyyyyyyydhhyyyyhhdmmmmdhyyhhhhhdmdddy");
        kprintfln("hmmmmmmmmddddddddhhddmmmmmddmNdddddmNNNmmmmdo+//::--.----/ydddddhhyyyyhdddyyyhhhhhhdmmdhhhhhdmmmmmmy");
        kprintfln("hmmmmmmmmddhhhhdddhddmmmddddddddddddmmNmmmdh/:/++ooo+++/:/yddddddhyyyyydhhyhdddhyyyyhhddhhdmmmmNNmmh");
        kprintfln("hmmmmmmmmdhdddddmmdhhhddddmmmddddddmNmmmmdds//+++osssyys++hddddddhyyyyyyhhyyhdddhhyhhyyhhddmNNNNNNmh");
        kprintfln("hmmmmmmmmdhdmmdhhdhdddhhdmmmmmddddddddmmmhso+++++++ssossosddddddhhyyyyyhdddhhddhhhdddhhddddmNNNNNNmh");
        kprintfln("ydmmmddhhhddmmmdhhhmmmmdhmmmmmddddmddddddhooo++oo++oo+ossyhdmmdhyyhyyyyhddmmhhddhhhhhhdmdddmNNNNNNmh");
        kprintfln("ymddhhhhhhhhhhhhhhhdmmmmhdmmmdhhhdddhhhhyyyyo++oo++sssyhhhhhhhyyyhhyyyyhddmdhmmmdhyyhdmmmddddmmmNNmh");
        kprintfln("shhhhddhhhhdddhhhhhhhddmhhdmmdhhhhhhdmmddhysooooooossshdddhhdddhyyyyyyyhddmddmmmdhyyhhdhdddddddmNNmh");
        kprintfln("syhdddddddmmddhhdddhhhdddhhddhyyyhhdmddyoyo+++o//oosyhhhhhhhdddddhyyyyyydddhdmmmhhhhyhhdddhddddddmmh");
        kprintfln("syhddddddddddhhhdddhyyhhhhhhyyyyyyyyo+:--o///++//oshhhyyyhhhhyhddddyyyyyhhyyhddhyhddhhdddmmdmmmmdddy");
        kprintfln("shhddmddmddddhyyyyyyyyyyhdddhso/:--...``.+++++///ooyossyydddhyyhddhyyyyyyhdhyyyyhhdmdhhhddmdmmmmmddy");
        kprintfln("shdddddddddhhhyhhhhyyyyyhy+:-.....```.```+yooo+++osy--:/syhddyyyyyyyyyyyhdddhyyyhhhhhhhhdmmddmmmmddy");
        kprintfln("shhhhhhhhyyyyhhddhhyyyyys:..````````..``.oyysssysyhs.....-/syhhyyyyyyyyyhhddhyyyhdmddhhhhddddddmmmdy");
        kprintfln("syyyhhhhhyyhdddddhyyhhyy/.``````````````./+ssssyyys:........-ohyyhhyyyyyhddhyyhdhdmmmmdhhyyyyyhdmmmy");
        kprintfln("syhddddddhyhhdddhhyyhhhs.`````````````````-+++++oo-..........:yyyhhyyyyyhdhyyyhmddmmNmNmdhhhhhhhhddy");
        kprintfln("shdddddddyyyyhddhyyhhhyo.`````````````````.+o++///-..........-yyyhhyyysyhhyyyhdmmddmmmmNmddmdddmdddy");
        kprintfln("syhdddddhyyyyhhdhyyhhys/.``````````````````/+oo//:.........``-yyyyyyyyyyyhyhhhhdmmddmmmddhdmdddmmmmy");
        kprintfln("oyyhddhyyyhhhyyyysyyyy+/.``````````````````:+++//:.``...````.-yhyyyhyyyyyyydhhhhdmddmmmddddddddmmmdy");
        kprintfln("shyyyyyyhdddhyssssyyho:.```````````````````-++///:.`````````.:yhhhyhyyyyyyyhdmddhhhhddddmmdhhhhmmdhy");
        kprintfln("syhyyyhhhhhhhhyysyhhs/.````````````````````-++/::--`````````./hhhhhyyyyyyyhdmmmmdhhhhhdmmmmdhyyhhhdh");
        kprintfln("yhhyyyhhhhhhhhyyyyhy/.`````````````````````./::::-.`````````.+hhhhhhyyyyyyhdddddddhhhhddddddhyyyhddy");
        kprintfln("yhhyyyhdddhhhhhyyys:.``````````````````````.:--::-.````````.-ohhhhhhyyyyyyhdddmmmdhyyhdddddddhyyhddh");
        kprintfln("yhyyyyhddhhhhhyyyy+.....```````````` ``````.::::--.````````.:yhhhhhhyyyyyyyyhdddhyyyyyddddddhhyyhdmh");
        kprintfln("shyyyyhhhhhhhhysyyo..`````..````````  `````.-:::-..`````````-oyhyyyyyyyyyyyyyyyyssyssyhhhhhhhhyyyhdy");
        kprintfln("sysssyyhyyyyyysssy+.``...`````   `     ````.-----.```````````.oyyyyyyyyyyyyyysssyyysssyhhhhhhhysyhdy");
        kprintfln("+soooossssssssoooo:````.----.`````      ```..---..``````` ````-/osssssssssssssssssssoossyyyyyysssyys");
        kprintfln("/o+/+ooooooooo++++:.`.-/::----..``       ````...````` ``      ``-/++ooooooooo++++oo+++oooooooo+++oo+");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();
        kprintfln("syhhhyyyyyyyyyyyyyyhhhhhhhhhhyyyyyyyyhhhhhhhhyhhyyyyhhdhdhhhhhyysssssssyhhhyyyhhyyyyyyyyyyysssssyyy:");
        kprintfln("yhhhhhhhhhhhhhddhhddhhhhhhhhhhhhhhhhdddhhyyyyyyyyyhhhhddddhdddddhyyyyyyyhddddddddhhhhhhhhhhyyyyyyyy/");
        kprintfln("yhhhhhhhhhhddmmdhdmmddddhhhhhhhhhhhhyyyyyyhyyyyhddmdddhhhhhhhhhhhyyyyyyyyhhhhhhhddhhddddhhhyyyyyyhy/");
        kprintfln("yhhhhhhhdddmmddhhdmmdmmmdmmmmmdhhhhhddhhhyyyyhhdmmmmmmdhhhhhhhyyyyyyyyyyyyhddddmmmdddmddhhyyyyhhhhh/");
        kprintfln("shhhhhddmmmmdhhddmmmdmmmmmmmmddhhhhhdddddhyyddmmmmmmmmmddhhdddddhyyyyyyddddmmmmmmmmdddmdhyyyyyhhhhh/");
        kprintfln("shhdddhhddddhhdmmmmmdmmmddhhdddhhhdhhhhyyyyyhhddmmmmmmmmddhhhhyyyyyyyyyyhddddmmmmmmdhhhhhhhhyyhhhhh/");
        kprintfln("yddmmmmdhhddhdmmmmmmdhhhhhhddmdhhhyyso++oo+osyyddmmmmmhhhhhhhyyyyhhyyyyyyyyyhddmmmmmdhyyhdddhhhhhhh/");
        kprintfln("hmmmmmmdddhddmmmmmdhhdddhhhmmmdhso+::---:::::+yyhddddhhhhdddddhyyyyyyyhdhyyyyyhhdmmddhyyyhhhhddddhh/");
        kprintfln("hmmmmmmmmddhddddhhhhdmmmmdddmmdy+:-----:/+/:-:shyhhhhddddddddddhhhyyyyhddhyyyhhhhhhddddhyhhhdmmmmmd/");
        kprintfln("hmmmmmmmmdhhhhhddhhddmmmddddddhyo/::/+osssso/:/hhhhhdddddddddddddhyyyyydhyyhhddhyyyyhdddhhdmmmmmmmm+");
        kprintfln("hmmmmmmmmdhhddhddmdhhhddhhdmmdhhs++ooooosssso//yyyyyhddddddddddddhyyyyyyyhyhhddhhyyyyyhhhdmmmNNNNmm+");
        kprintfln("hmmmmmmmddhdmmhhhdhdddhhdmmmmdhhyo++/++o++ossoosyhhhyyyyhdddddddhhyyyyyhdddhhdhyyydddhhddddmNNNNNmm+");
        kprintfln("yddmdddhhhddmmmdhhhdmmmdhmmmmdhhhhs+//+ososssssyhddddhyyyydddddhyyyyyyyhddmdhhddhyhhhhmmdddmmmNNNNm+");
        kprintfln("ydddhhhhhhhhhhhhhyhdmdmdhdmmmdhhhhyo+++oosssssydddddddhhhhhhhyyyyhhyyyyhddmdhmmddhyyhmmmdddddmmmmmm+");
        kprintfln("shhhhhhhhhhddhhyhhhyhdddhhdddhhhhhyyo+++ooossoosyhddddddddhhhhhyyyyyyyyhddmhdmmddhyyhhdhdhhhhhdmmmm+");
        kprintfln("syydddddddddddhhddhyyhddhyhhdhyyyhhdho+/+oooo+//+sooooossssyhdddhyyyyyyydddhdmmdhyhyyhhddhhhdddddmm+");
        kprintfln("syyddddddddddhyhddhhyyhhhhhhyyyyyhddho+///++o+//+o-........-:shhhhhyyyyyhyyyhddyyhddyyddmmddmmmmddd/");
        kprintfln("syhddddddddddyyyyyyyyyyydddddyyyyyyy:-//////+///+y/..........:yhhhhysssyyhhhyyyyhdddhyydddddmmmmmdh/");
        kprintfln("shdddddhddhhyyyyhhhyyyyhdddddyyyso/-..:o++++oo++shs...........+yyyyysssyhdddyyyyhhhhhyyhddddddmmddh/");
        kprintfln("shhhhhhyyyyyyyhddhhyyyyyydddhso/-..````/ssoosossyyo...........:yyyyysssyhhhhyyyyhdddhhyyhdddddmmmdd/");
        kprintfln("oyyyhhhhhyyhhdhdhhyshhyyyyhy+-.````````.+syysosyos+-......```.-oyhhysssyhhhyyyhhhdmmmdhhyyyyyydmmmd/");
        kprintfln("oyhhdddddyyhhdhhhysyhhhyso/..```````````.://////+++-......```.-/yhhyyyyyhdhyyydmddmmmmmmdhhhhhhhhhh/");
        kprintfln("shddddddhyyyyhhdhyyhhhyyo.````````````````.:/+//++/:.......``.-/yhyyyyyyhhyyyhmmmddmmmmmdhhdddmmdhh/");
        kprintfln("oyhddddhhyyyyhhhyyyhyyss+.`````````````````-/////++/-....````.-/syyyyyyyhyyhhhhdmdhdmmmdhhhdddmmmmd/");
        kprintfln("oyyhddyyyyhhyssyysyysyyy/.``````````````````-///+++/-...`.````.--+yhyyyyyyydhhhhddhdmmddhhhdhdmmmmd/");
        kprintfln("syyyyyyyyhddhysssssyhhhh/.```````````````````-//+//:-.````````.--+yyyyyyyyyhdddhhhhhdhddddhyyhdmdhh/");
        kprintfln("syyyyyyhhhhhhhyssyyhhhhhs.```````````````````.-////:-.`````````.-:syyyyyyyhdmdmmdhhhhhdmmmdhyyyhhhd+");
        kprintfln("yhhyyyhhhhhhhyyssyhhhhhho.````````````````````-////::-``````````--oyyyyyyyhdddddddyyyhhdddhhhyyhhdd+");
        kprintfln("yhhyyyhhhhhhhhysssyyhhhy/`````````````````````-://:---```````````.:syyyyyyhddddmdhyyyhdddddhhyyhhdd+");
        kprintfln("yhyyyyhhhhhhhhyssyyyyhhs-```````  ````````````.-:/::--.```````````-:yyyyyysyhhhhyssssyhhhhhhhyyyhdd+");
        kprintfln("shyssyhhhhhhhhyssyyysss+.```````   `````  ````.../:---.`````````.-:/syyyyyyssyyssssssyhhhhhhhyyyydd+");
        kprintfln("oyssssyyyyyyyysssyyyyso/.``````            ```..`-----.```````..-//:/osyyyyyssssyyysssyyyyyhyyssyhh/");
        kprintfln("+ooooossssssssooosssoo/-````                 `..``....```````.-:.-:-/+osssssssossssooosssssssssssyy/");
        kprintfln("/o+/+ooooooooo+++o++++/.``                    ``````````  ```.-/:--://+o+ooo+++++oo+++oooooooo+++oo:");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();
        kprintfln("syhhhyyyyyyyyyyyyyyhhhhhhhhhhyyyyyyyyhhhhhhhhyhhyyyyhhdhdhhhhhyysssssssyhhhyyyhhyyyyyyyyyyysssssyyy:");
        kprintfln("yhhhhhhhhhhhhhddhhddhhhhhhhhhhhhhhhhdddhhyyyyyyyyyhhhhddddhdddddhyyyyyyyhddddddddhhhhhhhhhhyyyyyyyy/");
        kprintfln("yhhhhhhhhhhddmmdhdmmddddhhhhhhhhhhhhyyyyyyhyyyyhddmdddhhhhhhhhhhhyyyyyyyyhhhhhhhddhhddddhhhyyyyyyhy/");
        kprintfln("yhhhhhhhdddmmddhhdmmdmmmdmmmmmdhhhhhddhhhyyyyhhdmmmmmmdhhhhhhhyyyyyyyyyyyyhddddmmmdddmddhhyyyyhhhhh/");
        kprintfln("shhhhhddmmmmdhhddmmmdmmmmmmmmddhhhhhdddddhyyddmmmmmmmmmddhhdddddhyyyyyyddddmmmmmmmmdddmdhyyyyyhhhhh/");
        kprintfln("shhdddhhddddhhdmmmmmdmmmddhhdddhhhdhhhhyyyyyhhddmmmmmmmmddhhhhyyyyyyyyyyhddddmmmmmmdhhhhhhhhyyhhhhh/");
        kprintfln("yddmmmmdhhddhdmmmmmmdhhhhhhddmdhhhyyso++oo+osyyddmmmmmhhhhhhhyyyyhhyyyyyyyyyhddmmmmmdhyyhdddhhhhhhh/");
        kprintfln("hmmmmmmdddhddmmmmmdhhdddhhhmmmdhso+::---:::::+yyhddddhhhhdddddhyyyyyyyhdhyyyyyhhdmmddhyyyhhhhddddhh/");
        kprintfln("hmmmmmmmmddhddddhhhhdmmmmdddmmdy+:-----:/+/:-:shyhhhhddddddddddhhhyyyyhddhyyyhhhhhhddddhyhhhdmmmmmd/");
        kprintfln("hmmmmmmmmdhhhhhddhhddmmmddddddhyo/::/+osssso/:/hhhhhdddddddddddddhyyyyydhyyhhddhyyyyhdddhhdmmmmmmmm+");
        kprintfln("hmmmmmmmmdhhddhddmdhhhddhhdmmdhhs++ooooosssso//yyyyyhddddddddddddhyyyyyyyhyhhddhhyyyyyhhhdmmmNNNNmm+");
        kprintfln("hmmmmmmmddhdmmhhhdhdddhhdmmmmdhhyo++/++o++ossoosyhhhyyyyhdddddddhhyyyyyhdddhhdhyyydddhhddddmNNNNNmm+");
        kprintfln("yddmdddhhhddmmmdhhhdmmmdhmmmmdhhhhs+//+ososssssyhddddhyyyydddddhyyyyyyyhddmdhhddhyhhhhmmdddmmmNNNNm+");
        kprintfln("ydddhhhhhhhhhhhhhyhdmdmdhdmmmdhhhhyo+++oosssssydddddddhhhhhhhyyyyhhyyyyhddmdhmmddhyyhmmmdddddmmmmmm+");
        kprintfln("shhhhhhhhhhddhhyhhhyhdddhhdddhhhhhyyo+++ooossoosyhddddddddhhhhhyyyyyyyyhddmhdmmddhyyhhdhdhhhhhdmmmm+");
        kprintfln("syydddddddddddhhddhyyhddhyhhdhyyyhhdho+/+oooo+//+sooooossssyhdddhyyyyyyydddhdmmdhyhyyhhddhhhdddddmm+");
        kprintfln("syyddddddddddhyhddhhyyhhhhhhyyyyyhddho+///++o+//+o-........-:shhhhhyyyyyhyyyhddyyhddyyddmmddmmmmddd/");
        kprintfln("syhddddddddddyyyyyyyyyyydddddyyyyyyy:-//////+///+y/..........:yhhhhysssyyhhhyyyyhdddhyydddddmmmmmdh/");
        kprintfln("shdddddhddhhyyyyhhhyyyyhdddddyyyso/-..:o++++oo++shs...........+yyyyysssyhdddyyyyhhhhhyyhddddddmmddh/");
        kprintfln("shhhhhhyyyyyyyhddhhyyyyyydddhso/-..````/ssoosossyyo...........:yyyyysssyhhhhyyyyhdddhhyyhdddddmmmdd/");
        kprintfln("oyyyhhhhhyyhhdhdhhyshhyyyyhy+-.````````.+syysosyos+-......```.-oyhhysssyhhhyyyhhhdmmmdhhyyyyyydmmmd/");
        kprintfln("oyhhdddddyyhhdhhhysyhhhyso/..```````````.://////+++-......```.-/yhhyyyyyhdhyyydmddmmmmmmdhhhhhhhhhh/");
        kprintfln("shddddddhyyyyhhdhyyhhhyyo.````````````````.:/+//++/:.......``.-/yhyyyyyyhhyyyhmmmddmmmmmdhhdddmmdhh/");
        kprintfln("oyhddddhhyyyyhhhyyyhyyss+.`````````````````-/////++/-....````.-/syyyyyyyhyyhhhhdmdhdmmmdhhhdddmmmmd/");
        kprintfln("oyyhddyyyyhhyssyysyysyyy/.``````````````````-///+++/-...`.````.--+yhyyyyyyydhhhhddhdmmddhhhdhdmmmmd/");
        kprintfln("syyyyyyyyhddhysssssyhhhh/.```````````````````-//+//:-.````````.--+yyyyyyyyyhdddhhhhhdhddddhyyhdmdhh/");
        kprintfln("syyyyyyhhhhhhhyssyyhhhhhs.```````````````````.-////:-.`````````.-:syyyyyyyhdmdmmdhhhhhdmmmdhyyyhhhd+");
        kprintfln("yhhyyyhhhhhhhyyssyhhhhhho.````````````````````-////::-``````````--oyyyyyyyhdddddddyyyhhdddhhhyyhhdd+");
        kprintfln("yhhyyyhhhhhhhhysssyyhhhy/`````````````````````-://:---```````````.:syyyyyyhddddmdhyyyhdddddhhyyhhdd+");
        kprintfln("yhyyyyhhhhhhhhyssyyyyhhs-```````  ````````````.-:/::--.```````````-:yyyyyysyhhhhyssssyhhhhhhhyyyhdd+");
        kprintfln("shyssyhhhhhhhhyssyyysss+.```````   `````  ````.../:---.`````````.-:/syyyyyyssyyssssssyhhhhhhhyyyydd+");
        kprintfln("oyssssyyyyyyyysssyyyyso/.``````            ```..`-----.```````..-//:/osyyyyyssssyyysssyyyyyhyyssyhh/");
        kprintfln("+ooooossssssssooosssoo/-````                 `..``....```````.-:.-:-/+osssssssossssooosssssssssssyy/");
        kprintfln("/o+/+ooooooooo+++o++++/.``                    ``````````  ```.-/:--://+o+ooo+++++oo+++oooooooo+++oo:");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();
        kprintfln("ohhhhhdddddmmmmmmmmmdddddmmmmmmmmmmmmmmmmdhyyyysssooo+/:::::///+oo+/+osysyyyhhhhhhhhhhhhhyyyyhhhhhhh");
        kprintfln("ohhhhhdddddmmmmmmmmmdddddmmmmmmmmmmmmmdddyyso+++//::::----------::::://:/+syyyyyyyyhyyhhhyyyyhhhhhhh");
        kprintfln("ohhhhdddddmmmmmmmmmmdddddmmmmmmmmmmmmdhhyysso/----:::-----........--------:////+oosyyyhhhyyyyyhhhhhh");
        kprintfln("ohddddddddmmmmmmmmmdddddmmmmmmmmmmddhysooo+/:........``.....``..............-:::::/+syhhhyyyyyhhhyyh");
        kprintfln("odddddddddmmmmmmmmmdddddmmmmmmdddhhys+:-::-...````````.............--.......---::///+syhyyyyyyhhyyhh");
        kprintfln("oddddddddmmmmmmmmmdddddddddddddhhso++/:---...```````.....----...................-:++++syyyyyyyhhyyhh");
        kprintfln("odddddddmmmmmmmmmmdhdddddddddddhys/://:-........````...........``.................-/++osyyyyyyhhhhhh");
        kprintfln("sddddmmdmmmmmmmmmdhddddmmmmddddhyys/-...........````````.............```.```````....-/+ssyyyyyhhhhhh");
        kprintfln("sddddmmmmmmmmmmmmdddddmmmddddddhhhyo/--........`````````......----........````````....:+ssyyyyhhhhhh");
        kprintfln("smmmmmmmNNNNNmNNmdddddddddddddddhhys+/:-......````````...----:::::----.....```````...-:/syyyyyhhhhhh");
        kprintfln("sddmmmmNNmNNmmmmdddddddhhhhhddddhhyyso/:-.............---:://++++//:::---....`````..-:/+oyyyyyhhhhhh");
        kprintfln("sddmmmmNNNNNNNNmddddddhhhhddddddmhyyyys+::---..----::://++oooosssso+/::---.....`....-:/+oyyyyyhhhhdd");
        kprintfln("sddmmmNNNNNNNNNmdddddddhhdmmmmmdmhyyyyyo+///:::::::///++oooossssssso+::---.........--::/osyyyhhhdddd");
        kprintfln("sdmmmmNNNNNNNNNmddddddddddmmmmmmmdhhyyyo+//////////////++oooossssyyo+/::---........--::/osyyyhdddddd");
        kprintfln("sdddmmmmmmmmmmmdddddmmmmmmmmmmdmmdddhys+////////////////++ooooossyys+//::---......---:/+oyyyyhdddddd");
        kprintfln("sdmmmNNNNNNNNNmdddddmmdmmmddddddddddhys+/////////:::////+++++oossssso+/::-----..----::++osyyhhhddddd");
        kprintfln("sddmmmmmNNmmNmddddddmmmmmmdmmmmmmddddys+/////////:::///+++++++oosssss+/::::::--------:/++ssyhhhhdddd");
        kprintfln("sddmmNNNNNNNNmdddddmmmmmmmmmmmmmmmmmdhso+//////:::::///+++++++oosssssss+/:::::::::--::::+syyhhdddddd");
        kprintfln("sddmNNNNNNNNNmddddmmmmNNNNNNNNNNNmNmdyo+/::::::::::::://///+++oosssssssso+/:::::::::///:+yyhhddddddd");
        kprintfln("sdmmNNNNNNNNmdddddmmmmmmmNNNmNNNmmmmhy+::---:::::----------://++ossssssyso//::::://++ossoyyhdddddddd");
        kprintfln("sdmmNNNNNNNNmdddddmNmNNNNNNNNNNNmNNmdhy+/::---::::::--.---:::////+ossssyso+/////+++++o+oyyhhdddddddd");
        kprintfln("sdmmNNNNmmmmddddddmmmmmmmmNmmmmmmmmmdhys/:::::://:::::-----:////++osssyyyso++oso++/+oso+yhhhdddddddd");
        kprintfln("sdmNNNNNNNNmdddddmNNNNNNNNNNNNNNNNNmdhhy+///::/+o+//:::---::/++++oosssyyyssssyyyo////ooshhhddddddddd");
        kprintfln("smmNmNNNNNmddddddmmmNNNNNNNmNNNNNNNddhyo//////+osoo++/::::://+++ooosssssssssyysso++++oyhhhhddddddddd");
        kprintfln("smNNNNNNNNmdddddmNNNNNNNNNNNNNNNNNmddhyo///+++osssso+/::::://+++oooossssssssssoo+osssyhhhhhddddddddd");
        kprintfln("smmmNNmmmmmdddddNNNNNNNNNNNNNNNNNNmddhhs+/+o++oossso/:::::://+++oooooossssssso+o+ossydhhhhhddddddddd");
        kprintfln("smmmNNNNNNdddddmNNNNNNNNNNNNNNNNNNddddhho//+/+++++oo+:::::://+++oooosssssssss++ooooohdhhhhhddddddddd");
        kprintfln("smmmmmmmmmdddddmNNNNNNNNNNNNNNNNNNdddddds/::::::::://:::::://++ooooosssssssssssssysshdhhhhhddddddddd");
        kprintfln("smmmmmmmmmddddmmNmNNNmmNNmmmmmmmmmdddddmh+/:::::://////:::://++ooooosssssssssssssyhhmdhhhhhddddddddd");
        kprintfln("smmmmmmNmdddddmNNmNNNmNNNmNNNmNNNddddddmds//:::::://////::::/++ooooooosssssssssssyhhdhyyyyhhdddddddd");
        kprintfln("smmmmmmmmdddddmmmmNNmmNNmNNNNmNNmdddhddmmds/:::::::::::::::://+++oooooooossssssssyhhhyyyyyyyhhhhhhhh");
        kprintfln("sdmmmmmmdhhhddmmmmmNmmNNmmNmmmmmdhhhhhddmdy/::::---::/:::::::///++++++ooooooooosssyyyyssosssyyyyhhhh");
        kprintfln("ohddhddhyyyyhddddddddmmmdmmmdmmdhyyyyhdddy-...--::-:+o/:::::::///////+++++++++oooossoooo/:/+ooossssy");
        kprintfln("+yyyyyysssssshhhhhhyhhhhyhhhhhhhsssssyyyys::-.....`-:.---:::::::::::://////////+++++:/++/....:/+++++");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();

        kprintfln("yyyyyyhhhhhdddddddddhhhhhddddddddddhdddddys+:-.....------:::::::---....```````          `.:////ossyy");
        kprintfln("hhhhhhdddddmmmmmmmmmdddddmmmmmmmmmmmmmdmmhyyo+::::::::////++++++//:---......``````    `````.-:+oyyyy");
        kprintfln("hhhhhhddddmmmmmmmmmdddddmmmmmmmmmmmmmmmmmhyyso+///::::///+++++++++/::--......```````````````.-/oyyyy");
        kprintfln("hhhdddddddmmmmmmmmmdddddmmmmmmmmmmmmmmmmdhyso+/////:::///+++++ooo+/:--......````````````````.-/+yyyy");
        kprintfln("hhddddddddmmmmmmmmddddddmmmmmmmmmdddddddhyso++////:::://////+oooo+/::--.....``````````````...-/+syyy");
        kprintfln("dddddddddmmmmmmmmmdhddddddddddddhhhhhhyyyys++/////://///////+ooooo//::-.....`````````````...-:/+syyy");
        kprintfln("ddddddddmmmmmmmmmdhhhhdddddddddddhhhhhyyyy+////////////////++ooooo+/:--........````````.....-:++oyyy");
        kprintfln("ddddddddmmmmmmmmmdhhhdmmmmmddddddddddddhyo////:::::::::///+++oooooo+/:------...............--/oooyyy");
        kprintfln("dddddddmmmmmmmmmddhhhdmmddddddddddddddhy+::::::----.----::/++oooooooo+/:---------.-.......--:/ossyyh");
        kprintfln("dddmmmmmmmNNNmNNmdddddddddddddddhhhhdddhs//::///::-----:::::/++ooooosso/:::::---------------::/+yyyy");
        kprintfln("dddmmdmmmmNNmmmmddddddhhhhhhddmdhhhhhhhhyo:/+/////:-...---:://+ooosssso+/:::::::------------:/:/yhhh");
        kprintfln("dddmmmNNNNNNNNNmddddddhhhhdddddmmhhyyhhhhyso/////:::::::::////+oossssso+//::::::::::/+/:--.--::+yhhh");
        kprintfln("dddmmmNNNNNNNNNmdddddddhhdmmmmmmmhhyyhhhys+//////:::::::////++ooosssssss+///++////////oo+:--:::shhdd");
        kprintfln("dddmmmNNNNNNNNmddddddddddmmmmmmmdhhhyhyy++ooo+//::::::::///+++ooooosssssssosys+/+///++/+o:-.-:/yhddd");
        kprintfln("ddddmmmmmmmmmmmdddddmmmmmmmmmmdmmdddhhy+++++o+/:::::::::///+++ooooooossssssyyyso+/:/+o+++:-.-:ohhddd");
        kprintfln("ddmmmNNNNNmNNmdddddmmmdmmddddddddddhhyys+/::::::::::::::///+++oooooooosssssssoso/////s++:----+hhhhdh");
        kprintfln("dddmmmmmNmmmmmdddddmmmmmmdmmmmmmmdddhyyyso+//::::::::::///+++++oooosssssssssoo+/+o++oo+-----/yhhhhhh");
        kprintfln("dddmmNNNNNNNNmdddddmmmmmmmmmmmmmmmmmdhyyyyo///::::::::///+++++oooosssssssss+////+ssoo/-..--+yhhhdddd");
        kprintfln("dddmNNNNNNNNNmddddmmmmNNNNNNNNNNmNNmdhhyys+//:::::::::///+++++oooosssssssso/:///+ooo/:-.-:+yhddddddd");
        kprintfln("ddmmNNNNNNNNmdddddmmmmmmmNNNmNNmmmmmhhyyy+/::-:::---:::///++++ooooossssssso+ooooooso/:--:oyhdddddddd");
        kprintfln("ddmNNNNNNNNNdddddmmNmNNNNNNNNNNNNNNmdhhhyso/::::::::::::///++++oooooossssssooooossso/::/syhhdddddddd");
        kprintfln("ddmNmNNNmmmmdddhdmmmmmmmmmmmmmmmmmmdhhhhhdho/::::::::::::///+++++ooooosssoooooossss+//oyyhhddddddddd");
        kprintfln("ddmNNNNNNNNmdddddmmmNNNNNNNNNNNNNNNddhhhdddy+/:::::::////////++++++oooooooooooossssoosyhhhhddddddddd");
        kprintfln("dmmmNNNmmmmdddddmmmmNNNmNNNmNNNNNNmddhhhdmmho/::::::///+/////+++++++ooooooooooosssyyhdhhhhhddddddddd");
        kprintfln("dmNmNNNNNNmdddddmNNNNNNNNNmNNNmmNNmdhhhddddy+/::::::////////////++++ooooooooooosssyhddhhhhhddddddddd");
        kprintfln("dmmmNmmmmmdddddmNNNNNNmNNNNNNNmNNNdddhhdmmmdyo//:::::///////::///+++oooo++++ooosssyhddhhhhhddddddddd");
        kprintfln("mmmmNNmmmmdddddmNNNNNNNNNNNNNNmNNmdhhhddmmmmmddhys+///:::::::::/++oooo++++++oossssyyhhhhhhhddddddddd");
        kprintfln("dmmmmmmmmmddddmNNNNNNNNNNNNNNNNNNmdhhhdmmmmmmmmdy++s+/:::://///+ooooooo++++ooossssyyyysyyyhddddddddd");
        kprintfln("ddmmmmmmmdddddmmmmmmmmmmmmmmmmmmmdhhhhdmmmmmdyo/:+so+/:::://///+oooooooooooooossssysyy+/+syhhhhhddhh");
        kprintfln("mmmmmmmNmdddddmmmmmmmmNNmmmmmmmmmhhhhyyyso+/::::/o++//:::::::///+++oooooooooooosssooyy/:-:+syhhhhhhh");
        kprintfln("mmmmmmmmddddddmmmmmmmmmmmmmmmmmdys+/::-------:--oo+/:::::::::::////++++ooooooooso/:oyy/-...-+osyhhhh");
        kprintfln("dmmmmmmdhhhhhmmmmmmmmmmmddhso+/:--.......------/o+/:::::::::::::::////++oooooo+/::/sys:......-:/+ssy");
        kprintfln("hddhhddhyyyyhdddddddhys+/::---..`````````:``..--:-::oo:-----------:::///++++/:---/osso-.`````````.-/");
        kprintfln("yyyyyyysssssshhyyo+::---...`````   ``   `.--...```.::.---------------::://:-----/+ooo:.`````````````");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();

        kprintfln("oyyyyyhhhhhdddddddddhhhhhdddddddddddddddddyyyyyhddhhhhhhhhhhhhdddhyyyyhhhhhhhyhhyyhhhhhhhyyyyhhhhhhh");
        kprintfln("shhhhhhddddmmmmmmmmmdddddmmmmmmmmmmmmmdddhyyyyhdddhddhhddddddddddhhhhhdddddddhddhhdddhddhyyhhhdddhhh");
        kprintfln("shhhhhhddddmmmmmmmmddddddmmmmmmmmmmmddhhhyssssyhhhhhhhhdddmmmmmmmhhhhhdmddddddddddddddddhyyyhhdddhhh");
        kprintfln("yhhddhddddmmmmmmmmmddddddmmmmmmmmddhhysoo++++oooosssssyyyhhdddmmdhhhhhdddddddddddddddddddyyyhhhhhhhh");
        kprintfln("yhddddddddmmmmmmmmddhhdddmmdddddhhso/::::://+//:///////++osyhhddhhhhhhddddmmdmmmddmmddmddhhhhhhhhhhh");
        kprintfln("yddddddddmmmmmmmmmdhhhhhhhhhhhyyso+/-://////::----....-:-:/+oosssyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
        kprintfln("ydddddddmmmmmmmmmdhhhhhhhhhhyyo+++/:/+//-----......```....-///+++oosyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh");
        kprintfln("yddddmdmmmmmmmmmmdhhhhdddhyys+//:::----.....`````````......--:://::/osyhhdddhhhhhdddddddhhhhhhhhhhhh");
        kprintfln("yddddmdmmmmmmmmmmdhhhhhhysoo+:-.....```.....````.........---::///--/++oyhdhhhhhhhddddddddhhhhhddhhdd");
        kprintfln("hmmmmmmmNmNNNmNNmdhhhhyss+//::-....````.................-----::::::////+syhhhhhhhhhddddhhhhhhhhhhhhh");
        kprintfln("hddmmmmNNmNNmmmmddhhhhyoo//:--.......````````.................---:::::::/oyhhddhhhhhhdddhyyyhhdddddd");
        kprintfln("hdmmmmNNNNNNNNNmddhhhhys+/:--......````````````.....````````..----:--:::/+yhdddddhhhhhhhyyyyhhdddddd");
        kprintfln("hdmmmmNNNNNNNNNmdddhhhys+/::-.........````````````````````....---------:/+hddddmmdhyyyyyyyyhhddddddd");
        kprintfln("hdmmmmNNNNNNNNmdddddhhhyo//:--..............```.............---:-------:/shddmmdddhyyyyyyyyyhddddmmd");
        kprintfln("yddmmmmmmmmmmmmdddddddhs+/:::-----------.............----:://////:-----:/sddddddddhhhyyyyyyyhddddddd");
        kprintfln("ydmmmNNNNNmmNNddddddddhs/:----::::::::::::::---::://++ooossssssso/:---::+shddddddddhddhhyyyhhddddddd");
        kprintfln("yddmmmmmNNmmmmddddddmdyo:--.-::////////////////++ooooossyyyyyyyss+/:::/++shhhhhhhhhhhhhhyyyhhddddddd");
        kprintfln("hddmmNNNNNNNNmdddddmmdho--.--:///////::///////+++oooooossyyyyyyyso+:::/+oyhdddddddhhhdhhhhhhdddddddd");
        kprintfln("hddmNNNNNNNNNddddddmmdho--.-:://////:::://////+++++++oosssssyyyyso+/::/osyhdddddddhddddhhhhhdddddddd");
        kprintfln("ydmmNNNNNNNNmdddhdmmmdds:---:://///:::::///+++++++++oooossssssssso+/:/+syhdddddmmmdmmmdhhhhddmmdmmmd");
        kprintfln("ydmNNNNNNNNNdddhhdmmmmmy/--:://::::::::::///+++++++oooosssssssssso+::/oyhdddddddddddmmdhhhhddddddmmd");
        kprintfln("ydmmmNNNmmmmdhhhhdmddddh/:::///:::::::::::///////+++ooosssssssssss+::+ydmddmdddmmmmmmmdhdddddddddmdd");
        kprintfln("hmmNNNNNNNNmdddddmmmddyo//:///::---------:::://:://+++ooosssssssss+:/ohdddddddddmddmmmddddddmmmmmmmd");
        kprintfln("ymmmNNNNNNmddddddmmmdy/////++/::::::--------:::::::::::///+ooosssso/+sddddmmmmmmmmmmmmdddddddddddddd");
        kprintfln("hmNNNNNNNNmdddddmmmmmh+//+ss+//::::::::----:::////::::::////++osyyo++oshddmmmmmmmmmmmmddddddmmmdmmmd");
        kprintfln("hmmmNNmmNmddddddmNNNmms/:+ss+//:::------:::::/oooo+/:::/++oooosyyyoosyohddmmmmmmmmmmmmddddddddddmmmd");
        kprintfln("hmmmNNmmNmdddddmNNNNNmy/:/oo+//::::::::::::::/osssso+///+oossssyyhoosyhdddmmmmmmmmmmmmdddddddddddddd");
        kprintfln("ymmmmmmmmmdddddmNNNNNNdo/:+o//::::::::::::::/+osssssooooossssyyyyhsooyhdhddddmmmmmmmmddddddddddddddd");
        kprintfln("hmmmmmmmmddddddmmmmmmmmh+//o//::::::::::::::/+osssssooooosssssyyyyysyhddddmmmmmmmmmmmdhhhhdddddddddd");
        kprintfln("hmmmmmmmmdddddmmmmNNNmNmhsss+/::::::::::::::/+osssoooooooosssssyyyyyhdddddddddddddmmmdhhhhdddddddddd");
        kprintfln("hmmmmmmmddddddmmmmmmmmNmmmmh+//::::::::::-::/++oooo++ooooooosssyyyyhdmmddddddddddddddhhhhhhhdddddddd");
        kprintfln("ydmmmmmdhhhhhdmmmmmmmmmmmmmho/:::::::::::/---::::///+++oooooossyhhhhdddddddhhhhhhhhhhyyyyyyhhhhhhhdd");
        kprintfln("yhdhhddhyyyyhddddddddmmddddh+:::--------::....--:-:/oo+++++ooosyyhhhhhhhhhhhhhhhyyhhysssssyyyyyyhhhh");
        kprintfln("syyyyyysssssshhhhhhyyhhyyyys+:------...-----...`.`.:--/////+++ossyyyyyyyyyyyyyyyyysssooooooooossssss");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();

        kprintfln("shhhhhyyyyyyyyhhhhhhhdhhhhyyyyyyyyyyssyyyyyyssssssyyyyyyysssyyhhysssssyyyyyyhhyyyyyyyyyyyyysssssssyy");
        kprintfln("yddhhhhhhhhhhhhhhdmmmmddmmdddddddhhhyyyyyyyyyyyyyddddddhhhhyyyyyyyyyyysyyyyyhddhhddhhhhhhhhyyyyyyyyy");
        kprintfln("yhhhhhhhhhhhhhddmmmmdhhdmmdmmmmmmmdhhyyhdddhyyyhddhhhhhhhhhhhhhhyyyyyhhddddddmmddmmmdhhhhhhyyyyyyyyy");
        kprintfln("yhhhhhhhhhhhdhdddmmdhdmmmmmmmmmmdddhhhhhhhhhhyhhy+/:::::/+shhhhyyyyyyhhdddmmmmmddddmmmmdhhyyyyyyyyyy");
        kprintfln("shhhhhhhhddmmmdhhhhhhdmmmmdddddddmmdhhdhyhhhhhys+:-...----:+yysyhyyyyyyyyhdmmmmmmdhdmmddhyyyyyyhhhyy");
        kprintfln("shhhhhhddmmmmmmddhhdmmmmddddddddmmmdhhhhhddddhs+//////////::shyyyyyyyhhyyyyhhdmmmdhhhhyyhdhhyyyhhhhy");
        kprintfln("shhhhdmmmmmmmmmmmdhdmmddhddmmmmddmmhhhhddddmmh//++oosssyys+:sdhhyyyyyddyyyhhyyhdmmmdhhhhdddddhhhhhhh");
        kprintfln("shhhhdmmmmmmmmmmmdhhhdddddmmmmdddddhhhhddmmmmy//++++ossssso/yddhyyyyyhyyhhddhhyhhddhyhddddmmmmdddhhh");
        kprintfln("shddhdmmmmmmmmmmmdhddddmmddddddmmmddhhhddmmmdyoo+++++os+ooosddddhyyyyyhhyhdhyyhdhhyyyhdddmmmmmmmddhh");
        kprintfln("ydmdhdmmmmmmmmmmdddmmdddddmmmdmNmNddhhhhhdddhooo+++++osssssyddhyyyyyyddddyyyyyhhyyhhyhdmmmmmmmmmdddd");
        kprintfln("ydddhhhhdmmmmdhhhhdddmdhhdmmNmmmmmddhddhyyyhhyso+++++osssssyhyyyhhyyyddddhdddhyyhdddyhdmmmmmmNmmmddm");
        kprintfln("yddhhhddddmddhhhhhhdhhhhhhdmmmdmmmdhhhhyhdddyhhs++++oosssyyyhhyyyyyyyhddhhmmmhyyhhhhhhhhdmmmmmdddddm");
        kprintfln("ydmmmmdmdhhhdmmddmmmmdhddhhdmmddmmdhhhhddddhyyy+++++oossyyyhdddhyyyyyhddydmmdhhhyhhhhhdddddmmddddddd");
        kprintfln("yddmmmdmdhhhddmddmmmdhhdddhhdhdddhhhhhdddhyyhhy+++++oossyyhyyyhhdhyyyyyyyhdhhdddyhddmmmmmmdhhdmmmmmm");
        kprintfln("yddddddddhhdddddddddhhhhhyyyyhddmdhhyyyhysoosyooo++oossss:ohyyyhhyyssyhhhyyyyhhdyyhddmmmmmdhhdmmmmmm");
        kprintfln("shhhhddddhhddddhhhhhyyhdhhyyyyhddhyyso/:-..-oo//++++oooy+...-:+syyyyyyhhhhyyyhhyyyyddddmmmmdhdmmmmmm");
        kprintfln("syyyhyhhhhhhhhhyhyyhhddddhhhyyyhs/:-..`````.so//+o++oyhy-..````..-/osyhhyyyyyhddhyyyyyyhddmdhmmmmddd");
        kprintfln("sydddddhhyyyhdddddyhdddddhhddyyy:.....``````:/:/+ooyyhy/...````.-..`.-+hyyyhyyhddmdhyyhhhyhhhddhdddh");
        kprintfln("syddddddhyhddddddhyyhdmmhhdddhy+..```````````-//////+o-...````-+ooo/-..oyyhhhyhddmdhyhddddhyyyhdmmmm");
        kprintfln("syhddddhyyyhdddddhyyyhddhhdhyys:.````````````.oo//++/:..``````:+ooss/../yyyyhyydddhyhdddddddyydmmmmm");
        kprintfln("yhyhdhhyhhyyhhhyyyhhhyyyyyyhhy..`````````````.ss/////-````````.:+ooo-`./yyyyyyyhhhhhhhhdddhyyyhdmmmd");
        kprintfln("ydhhhhhddddhhyyyhhdddhyyyhhdd+.```````````````/+///::.`````````-/+o+.`.+hhhhyyyyyhmmmdhhhhyhhhhhhddh");
        kprintfln("shhhhhhhhhhhhyyyhhhhhhhyydddh/.```````````````-:://:-``````````.:+o+.``:hhhhhhyyhddddddhhhdddddddhhd");
        kprintfln("yddhhhddddddhyyhddddddhyyyhy+-`````````````.`.-:::::.````````````.--.``-yhhddhyyhddddddhhhdddddmdhhd");
        kprintfln("yddyyhddddddhyyhdhhhhdhyyy+-..``````````.:/+///::::-```````````````````.:hhhyyyyhdmmmmmdhhdmdddmdhhm");
        kprintfln("ydhyyhddddddhyyhhhhhddhyy+......```..``.:/++++/:-::-````````````````````.+yyyyyyhddmmmmdhhdddddmdhhd");
        kprintfln("yhhyyhhhhhddyyyhhhhhhdhyy+.....```.````-://+++::---.````````````   ````````:shyyhdddmmmdhhdddddmdhhd");
        kprintfln("yhhyyhhhyyhhyyyhhhhhhdhyhh:.```````````.....``-::--`````````````    ````````.oysyhhhhhhhyyhdhhhddhhh");
        kprintfln("yhhyyhhhhhhhyyyhhhhhddhyhyo-...```..``````````.----`````````````     ```````/yysyhhhhddhyyhdhhhddhhh");
        kprintfln("shyyyhdddhhhyyyhhhhhddhyhhddhso//:/+-`````````.---.`````````````     ``````/yyysyhhhhhhhyyhhhhhddhyh");
        kprintfln("oyysyyyyyyyyysyyyyyyhhyyhhhhhhhhyyss:`````````.---.```````````````    ````:yyyyyyyyyyyyyyyyyyyyhhyyy");
        kprintfln("osssssssssssssssssssyyyyyyhhhyyyysss:`````````..````````````````````-::-:oyyyyyyyyyyyyyssssyyyyyysss");
        kprintfln("+ooooooooooooooooooosssssyyyyysssooo:`````````..````````````````````-osssssssssssssssssssssssssssooo");
        kprintfln("////+++++++++/++++++++++ooooooo+++++-`````   `..---`````         `````:+oooooooooooo+++++++++oo+++++");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();

        kprintfln("yhhdhhhhhhhhhhhdddddddhhdhhyyyhhhhhyyyyhhhhyyyyyyyhhhhhhhyyyhhdhyyyyyyhhhhhhddhhhhhhhhhhhhyyyyyyyyys");
        kprintfln("yhhhhhhhhhhhhhhhhdmmmdhdmddddddddhhyyyyyyyyyyyyyhddmmmdhhhdyyyyyyysyyyyyyyyhhddhdddhhhhhhhhyyyyyyyys");
        kprintfln("yhhhhhhhhhhhhhddmmmmdhhdmmdmmmmmmmdhyyyhdddhyyhddmmmmmmddhhhddhhyyyyyhddddddmmmddmmmddhddhhyyyyyyyys");
        kprintfln("yhhhhhhhhhhddhdddmmdhdmmmmmmmmmddddhhhhyhhhhhyhddmmmmmmmdhhddhhyyyyyyhddddmmmmmmdddmmmmdhhyyyyyhhhys");
        kprintfln("shhhhhhhhdmmmmdhhhhhhdmmmmdddddddmmhhhdhyhhhdhhhdmmmmmdhhhdhhyyydyyyyyyyhdmmmmmmmdddmmddhyyyyyhhhhhs");
        kprintfln("shhhhhhddmmmmmmddhhdmmmmddddddddmmmdhhhhhddmmmdhhddmmddddmmmmdhyyyyyhdhyyyyhhmmmmmdhhhyyhddhyyhhhhhs");
        kprintfln("yhhhhdmmmmmmmmmmmdhdmdddhddmmmmddmdhhhhddddddmdmmdhhhdmmmmmmddddhyyyhddyyhdhyhhmmmmdhhhddddddhhhhhhs");
        kprintfln("shhhhdmmmmmmmmmmmdhhhdddddmmmmdddddhhhhhyyso++oshdhhhdmmdmmdmdddyyyyyhyyhdddhhhhdddhhhdddmmmmmmdhhhs");
        kprintfln("shddhdmmmmmmmmmmmdhddddmmddddddmmmddhhhy/:::---::/+yhhddddddmdddhyyyyhdhyhdhhyhdhhyyyhddmmmmmmmmddhy");
        kprintfln("ymmdhdmmmmmmmmmmdddmmdddddmmmdmNNNdddhhs/:---------:shyyyhddddhyyyyyyddddyyhyyhhyhdhyhdmmmmmmNmmdddy");
        kprintfln("ydddhhhhdmmmmdhhhhdddmdhhmmmNmmmmNddhhhyooooosso+---/ddhyyyhhhyyhhyyyddmdhdmdhyyhddhyhdmmmNNmNmmmdmh");
        kprintfln("yddhhdddddmdhhdhhhhdhhhhhhdmmmdmmmdhhhyo+ooossyso:--sdddddyhhhhyyyyyydddhdmmmhhhhhhhhhhhdmmmmmddddmh");
        kprintfln("ymmmmmdmdhhhdmmddmmmmdhdddhdmmddmmdhhho+/+o++osso:::hddhhhyhddddyyyyyhddhdmmdhdhhhdhhddddddmmddddddy");
        kprintfln("yddmmmdmdhhhdmmdmmmmdhhdddhhdhdddhhhhyo++osooosso::ydhyyhhdhyhdddhyyyyyyyhdhhdmdyhdmmmmmmmdddmmmmmmh");
        kprintfln("yddddddddhhdddddddddhyhhhyyyyhddmmhhhy+++ooossssoosyysyhdmmmhyhdhyyyyydddyhhhhddyyddmmmmmmdhhdmmNmmh");
        kprintfln("shhhhddddhhddddhhhhhyyhdhhyyyyddddhhhy++++ooo+//+yyyyhdddmmmdhyyyyyyyhdddhhhhddhyyhdmmdmmmmddmmmNmmh");
        kprintfln("syyhyyhhhhhhhhyyyyyhhddddhhdyyydddhyyys++oooo+//ohyyyhdddmmmdhyyhyyyyhddhyyhyhddhhyyhhhhdmmddmmmmddy");
        kprintfln("sydddddhyyyyhdddddyhdddddhhdhyyhddyysy+////+o+//oyyyyyyhhddhyyyhhyyyyhdhyyhdhyddmmmhyhhhhyhhhddddddy");
        kprintfln("oyddddddhyhddddddhyyydddhhddhyysso+/+s+///+ooo++ooyyyyyyyhhyyyyhhyyysyhyyyhddyhmmmmhhdddddhhyhdmmmmh");
        kprintfln("syhddddhyyyhdddddyyyyhddyhhs+/-...`.:ys+//+ooosso.-:+oyyyyyhhyyyyyyssyyyhyyhdhhdmmhhhdddddddyhmmmmmh");
        kprintfln("yhyhdhhyhhyyhhhyyyhhhyyo/:-..```````+sysoo+++oyy/..``..-/+syyyhyyhyysssyyyyyyhyddhddhhhdddhyyyhmmmmh");
        kprintfln("ydhyyhhddddhyyyyyhhhhys-.```````````:++oooosyys+-..``````..:/shhyyyyyssyhhddyyhhhdmmmdhhdhyhdhhhdddy");
        kprintfln("shhyyhhhhhhhhyyyyhyyyy:.``````````````.:::/+os+-..`````````..:shhyyyssyhhhdddhhhddmmmmdhhhdddddddhdh");
        kprintfln("yddyyhddddddhyyhhhhhhy.````````````````:///////-.```````````..ohhyyyyyyhhddmmdhhdmmmmmmdhhdddddmdhdh");
        kprintfln("ydhyyhddddddhyshhhhhhs.````````````````-//////:-.````````````.+yyyyyyyysyhddhhhhdmmmmmmdhdmmmdmmdhdh");
        kprintfln("ydhyyhddddddysshhhhhh/.``````````````.:://///::-.````````````.+yyyyyyyyhyyyyhdhhdmmmmmmdhdmmdddmdhhh");
        kprintfln("yhhyyhhhhhhhyssyhhhhs-``````````````-/+++++//::-`````````````.+hhhyyyyyhhyyhddhhdmmmmmmdhhdddddmdhhy");
        kprintfln("yhhyyyhyyyyhysyyhhhy/.`````````````-:/++++/::::-`````````````.ohhhhyyyyhyyyyhdhyhddddddhyhdddhdddhhy");
        kprintfln("yhyyyhhhhyyhysyhhhhs-``````````````-:///:::---:-`````````````-oyyyyyyyyyyyhhyhyyhddddddhyydddhdddhhy");
        kprintfln("shyyyhddhhhhysyhhhh+.``````````````.--.```------`````````````./sysooosyyyhhhyyssyhhhhhhhyyhhhhhddhyy");
        kprintfln("oyysyyyyyyyysssyyyo-````````````..```` ```.-----``````````````./o+++++osyyyyyyssyyyyyyyyssyyyyyhhyys");
        kprintfln("ossssssssssssossss/````````````````    ````.----```````````````://:///+osyyyysssssssssssssssssyyyyso");
        kprintfln("+ooooooooooooooooo+-```````````         ```...-.`` `````      `.---://+oosssssooossooooooooosssssso+");
        kprintfln("///////+++////+++++/-````````            ```....```            ``...-//++++++++++++++++++++++++++++/");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();


        kprintfln(".--------------------------------------------:-------------------------.`                 `---::::::");
        kprintfln("----::::::::::::::--:::::::::::::::::::-:-----:::::::::::-::::-::::----.`                 `.:::////:");
        kprintfln("------:::::::::-----:::::::::::::::::::::::::::::::::::::----:--:::---.`                   .::::////");
        kprintfln("-:::::::::::::::-:------:::-------:::::::::::::::::::::::::::::::::---.``                  `-:://///");
        kprintfln("-:::::::::::::::::::::::::::::::::::::::::------------------:::::::----``````` ``  `` ``````-://////");
        kprintfln("--:::------------:------::-----..--::::::::::::::::::::::::::::::::::--`````````````````````.://////");
        kprintfln("-:::::::::::::-::::----..```````````.-://:::--:::::---:----::::::::---.`````````````````````.://////");
        kprintfln(".-::::::::::::::::--.```` ``````````````..::/:/::::::::::::::::::::---.`````````````````````.://////");
        kprintfln(".-:::::::::::::--.```  ` ```````........--:::://:--::::::::::::::::::-.````````````.........-://////");
        kprintfln("-:::::::::::::::-``````````...``````````.-::/o:++:::::::-::---::::::---....................-:///++++");
        kprintfln("-::::::::::---:.``````.```````    ```````.--://+//::::::::::::::::::::-............---------://///++");
        kprintfln("-:::::::::::--:.`..```````````   ```.....-::::::::----::/:::::--::::-----..-------------:::::///////");
        kprintfln("-::::::::::::::.`..`..`````..```````....:///::----::::::::::::::::::::------------:::::::::://///+++");
        kprintfln("-----------::--.````..-::///++//:--::///+osso:----::------------------------::::::::::::::://///++++");
        kprintfln("-:::::::::::::-.````.:/++ooossssooooooo++oyyyo/::::::::::::::::::::::::::::::::::://:::://////++++++");
        kprintfln("---:::::::::---.```.:/+++ooooooooooooo+++oyyhho/:::::::::::::--::::---:::::::::://////////////++++++");
        kprintfln("----:::::::----.```.:/++++oooooooooooo+++ossydy+//::::::::::::::::::::::::::::://////////////+++++++");
        kprintfln("-::::::::::::::-```.:/+++oooooooooooo++++ooshdyoo+::::::::::::::::::::::::::/::://///////////+++++++");
        kprintfln("----------------.``.////////:///++++//:::::+shhss/:::::::::::::::::::::::::://:::////////////+++++++");
        kprintfln("---------:-----::.`.///////:::::/++/--..---/oyysoo/:::::::::::::::::::::://////::::://///////+++++++");
        kprintfln("-::::::::::::::::+:-/++++/////+++++/://////++syss/:--::-::::--::::--:::://///////::://///////++++oo+");
        kprintfln(".--------:::::::+++//+++oo+++ooo++++//++++++oyy///::::::::::::::::::::::::://:://:::::::::://+++++++");
        kprintfln("--::::::::::::::/+o+/+++oooooooo+++++//+++++syyo+::::::::--:::-------:::::::/::::::::::::////+++++++");
        kprintfln("-:::--------::---/oo+++++o+/++++++++o+:://++syso:::::::::::::::::::::::::::::::::::::::::///++++++++");
        kprintfln("-------------:----://////::/++++//:-..-::::+sy/:::::::::::::::::::::::::::://::::::::::::/++++oooooo");
        kprintfln("-::::::::::::::::::::////:////++++/:::::--:+so:::::::::::::::::::::::::::////::::::::::::/++++++++++");
        kprintfln("---::---::::----:::///////+++///++//+:-::/+os/--:::::::----::-----------::::::::::::::::/++++ooo++++");
        kprintfln(".--::::::::::::::/++oo+///+++++++////+o++oo+:oo:-------:::::::-:::--::--::::::::::::::::/++++ooooooo");
        kprintfln("----::----------:+/+s:++///+++++/////++oso/``:+so//:-:::::::::::::::::::::::::::::::::::/+++oooooooo");
        kprintfln("----::::--::::/+o++so./++///++o+++++/+os+-.  `:oso/+++//:::::::::::::::::::::::::::::::::+oooooooooo");
        kprintfln("---::::::::+osysoosys../+////:/+++///++:..`  `:oss//+++osso/:::::::::/:::::::::::::::::::/++ooooo+oo");
        kprintfln("-:::::/+osssssso+oyys+``-////:-....---.``    `:oooo//+sysyyyyso/:::::::::-::::-----------/+++++++o++");
        kprintfln(".---:/oosssssos++osso+`` `.-:::-.`````       `/oooo//ossssssssssso/::::------------------:///////+//");
        kprintfln(".-//++++ooo+++++//+++/.      ``````           :++///::+oooo++++++ooo:--------------------:::://////:");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();

        kprintfln("-::-------------.......................``.``.......-........-------------::----:::::---....-----.--.");
        kprintfln("::/:::----------.........................................----------::::::::::::::----.....---------.");
        kprintfln("-:::::::------...................................----------------------::::::-...--------::::::::-..");
        kprintfln("```..-------------..........................---------::-----------------::::-.`..--.---:::::::::-...");
        kprintfln("``   ````....--...........................----------::::-----------------:::-```.--.--::////::---...");
        kprintfln("-//-```````.......................................------------------------:::-----.-:/++++++//:::-/+");
        kprintfln(" `-++/.``` ``........`......................``     ``..--------------------:::::--.-:+ossssoo++/:/dd");
        kprintfln("   `:oo/.``  ``.........................``  `.-`      ``.----------------------...`-//osssyssso+//ss");
        kprintfln("    `-oso-`````..................``....`      .::.      `.------------------.`      `:/+oossssoo+:+:");
        kprintfln(" `````/sso-`````......................``       `:/-`     `...--------::----``-.      `-//+oossoo/-+:");
        kprintfln("``````.osso`````......................`         .//-`    `.....------------` .-.`      .:/+ossss+-+/");
        kprintfln("`..```.+yys.`````.....```..`````````.````````````:++.`    `....----------:/`.+/:.      `-:/+ooss+:+/");
        kprintfln(".--....+yyy-``````````````.`````````.`.........../++-`   ``.....---------+. .o/:-`      .-://+++/-/:");
        kprintfln(":::::::+yyy:``````````````````..`````..----....::/++-``````.....--......-o. .o/:-`      ..--::::-.:-");
        kprintfln("///////oyyy:`````````````````````````..-----/+oo++oo-``````..............:/.-o/:-`      ...-----..-.");
        kprintfln("/++++++shyy:`````````````````````````..--:o+oo++/+oo-``````..............++`-+::-       `....---..--");
        kprintfln("+oo++++syyy:`````````````````````````.-+yhhh:.:y++oo-``````............../` -/::.       ````..--`.--");
        kprintfln("+oooo+osyy+.```````````````````````...odhhhhy.:yhso/.`````................` .::-        ````..-.``--");
        kprintfln("+ooooosyys-``  `````````.```````.....ohhhyhho`-yhyo......`.---------......` `-:-        ````.... `--");
        kprintfln("+oooooyhyo```  ````````````...`...../yyhyhhso+`:yso-.......------------...```-/-`      `.......` `--");
        kprintfln("+ooooosyys```  ``````````...........-osyyys+-- `+ys:.......---------------...:/-``     `.......` `--");
        kprintfln("/ooo++syys```  ``````................./ooys-`   .oyso:..-..----------.-------:/:````````.-..---. `-.");
        kprintfln("/+++++syys.``  ````..``````...........+sshy.`    -oo-..----::--..----.----....-.````````.----:-. `-.");
        kprintfln("+sssssyyys```` ````..```.............-osydo`     `-o-....--:::-.--------..`````````  ```.....``   ..");
        kprintfln("+ooooosyyo```` ``.......`````......../oohh/-``    `:+-....-:--...-...```````````````````````````````");
        kprintfln("/++ooossyo```   `.......``.````......++ohy.....    -//-...`...```````````````...`````````...........");
        kprintfln(":////:::-.`    `....````..``````.....///s+`-....   .-/-`````````````````````````````````````````````");
        kprintfln("``````.....```.`````               `.///+.`.....    .-:.........................``.......-..-------.");
        kprintfln(".----.....````          ````````````.:::/   ..`.    .-:-.````````...----------------........------:-");
        kprintfln("`````````````````````````````````````.---   `````   ````````````   ``````````````````````````.......");
        kprintfln("````````````````````````````````````````   `````   `````````````````````````````````````````````````");
        kprintfln("````````````````````````````````.......   ``````` `..................-................----------....");
        kprintfln("````````````                     `      ````````   ....``.......````...``.----::-:----------...----.");
        kprintfln("########################### User Programm <uart_listen> nicht eingebunden ##########################");
        kwait();
        clears();


    }
}